import * as React from 'react';

import { AdminPage } from '../components/AdminPage';

export const Pages = () => (
  <AdminPage title="Pagina's">
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
    Pagina's<br/>
  </AdminPage>
);
